version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MODEL_PROVIDER=ollama
      - OPENAI_API_KEY=
      - OLLAMA_MODEL=llama3
      - GITHUB_TOKEN_DEFAULT=
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: ["celery", "-A", "app.celery_app.celery_app", "worker", "--loglevel=INFO"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MODEL_PROVIDER=ollama
      - OPENAI_API_KEY=
      - OLLAMA_MODEL=llama3
      - GITHUB_TOKEN_DEFAULT=
    depends_on:
      - redis
